version: 1
formatters:
  standard:
    format: "%(asctime)s_%(name)s_%(levelname)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  # file_handler:
  #   class: logging.handlers.FileHandler
  #   level: DEBUG
  #   formatter: standard
  #   filename: 'logs/%(asctime)s.log'
loggers:
  standard:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]